# Generated by Django 4.2 on 2025-11-09 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0003_trainer'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='trainers/'),
        ),
    ]
