# Generated by Django 4.2 on 2025-11-09 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0004_trainer_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='trainer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pokedex.trainer'),
        ),
    ]
